# ../.zprezto/runcoms/zshrc
source ${0:a:h}/../.zprezto/runcoms/zshrc

stty -ixon

HISTSIZE=100000
SAVEHIST=100000

# Ignore rm command in history
# http://mollifier.hatenablog.com/entry/20090728/p1
zshaddhistory() {
  local line=${1%%$'\n'}
  local cmd=${line%% *}

  [[ ${cmd} != rm ]]
  # [[ # ${#line} -ge 5
  # && ${cmd} != (l|l[sal])
  # && ${cmd} != (c|cd)
  # && ${cmd} != (m|man)
  # ]]
}

# TODO: Check autosuggestions module: autosuggestions/README.md
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
zstyle :bracketed-paste-magic paste-init backward-extend-paste

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
# NOTE: lesspipe.sh can't load in zprofile so fail to existing check.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
  export LESS_ADVANCED_PREPROCESSOR=1
fi

setopt checkjobs
