# ../.zprezto/runcoms/zshrc
source ${0:a:h}/../.zprezto/runcoms/zshrc

# TODO: Check autosuggestions module: autosuggestions/README.md
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
# NOTE: lesspipe.sh can't load in zprofile so fail to existing check.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
  export LESS_ADVANCED_PREPROCESSOR=1
fi

# Load rbenv automatically by appending
# the following to your profile:
eval "$(rbenv init -)"
